### PR TITLE
pekko-projection 1.0.0

### PR DESCRIPTION
**Pull request by pjfanning**
* update doc versions to use numeric versions instead of 'current'

### CODE REVIEW

**Review by nvollmar — APPROVED** [review]
lgtm

**Review by mdedetrich — APPROVED** [review]
lgtm

**Review by mdedetrich — CHANGES_REQUESTED** [review]
It should be major.minor and not major.minor.patch for the doc version (in this case `1.0`)

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
